In [28]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import polars as pl
import numpy as np

# Set the path to the file you'd like to load
file_path = "lending_club_loan_two.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "jeandedieunyandwi/lending-club-dataset",
  file_path
)

print(df.columns)

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'purpose', 'title',
       'dti', 'earliest_cr_line', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'application_type',
       'mort_acc', 'pub_rec_bankruptcies', 'address'],
      dtype='str')

In [3]:
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,...,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,...,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,...,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,...,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,...,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [20]:
df.shape

(396030, 27)

In [5]:
df.dtypes

loan_amnt               float64
term                        str
int_rate                float64
installment             float64
grade                       str
sub_grade                   str
emp_title                   str
emp_length                  str
home_ownership              str
annual_inc              float64
verification_status         str
issue_d                     str
loan_status                 str
purpose                     str
title                       str
dti                     float64
earliest_cr_line            str
open_acc                float64
pub_rec                 float64
revol_bal               float64
revol_util              float64
total_acc               float64
initial_list_status         str
application_type            str
mort_acc                float64
pub_rec_bankruptcies    float64
address                     str
dtype: object

In [4]:
df['loan_status'].value_counts()

loan_status
Fully Paid     318357
Charged Off     77673
Name: count, dtype: int64

In [7]:
df.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,open_acc,pub_rec,revol_bal,revol_util,total_acc,mort_acc,pub_rec_bankruptcies
count,396030.000000,396030.000000,396030.000000,3.960300e+05,396030.000000,396030.000000,396030.000000,3.960300e+05,395754.000000,396030.000000,358235.000000,395495.000000
mean,14113.888089,13.639400,431.849698,7.420318e+04,17.379514,11.311153,0.178191,1.584454e+04,53.791749,25.414744,1.813991,0.121648
std,8357.441341,4.472157,250.727790,6.163762e+04,18.019092,5.137649,0.530671,2.059184e+04,24.452193,11.886991,2.147930,0.356174
min,500.000000,5.320000,16.080000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,2.000000,0.000000,0.000000
25%,8000.000000,10.490000,250.330000,4.500000e+04,11.280000,8.000000,0.000000,6.025000e+03,35.800000,17.000000,0.000000,0.000000
50%,12000.000000,13.330000,375.430000,6.400000e+04,16.910000,10.000000,0.000000,1.118100e+04,54.800000,24.000000,1.000000,0.000000
75%,20000.000000,16.490000,567.300000,9.000000e+04,22.980000,14.000000,0.000000,1.962000e+04,72.900000,32.000000,3.000000,0.000000
max,40000.000000,30.990000,1533.810000,8.706582e+06,9999.000000,90.000000,86.000000,1.743266e+06,892.300000,151.000000,34.000000,8.000000

In [8]:
df['earliest_cr_line'].head()

0    Jun-1990
1    Jul-2004
2    Aug-2007
3    Sep-2006
4    Mar-1999
Name: earliest_cr_line, dtype: str

In [5]:
df1 = df.copy(deep=True)

In [6]:
df1 = df1[['loan_amnt','term','int_rate','grade','home_ownership','annual_inc','loan_status','dti','emp_length','installment','revol_util','revol_bal']]
df1.head(20)

,loan_amnt,term,int_rate,grade,home_ownership,annual_inc,loan_status,dti,emp_length,installment,revol_util,revol_bal
0,10000.0,36 months,11.44,B,RENT,117000.0,Fully Paid,26.24,10+ years,329.48,41.8,36369.0
1,8000.0,36 months,11.99,B,MORTGAGE,65000.0,Fully Paid,22.05,4 years,265.68,53.3,20131.0
2,15600.0,36 months,10.49,B,RENT,43057.0,Fully Paid,12.79,< 1 year,506.97,92.2,11987.0
3,7200.0,36 months,6.49,A,RENT,54000.0,Fully Paid,2.60,6 years,220.65,21.5,5472.0
4,24375.0,60 months,17.27,C,MORTGAGE,55000.0,Charged Off,33.95,9 years,609.33,69.8,24584.0
5,20000.0,36 months,13.33,C,MORTGAGE,86788.0,Fully Paid,16.31,10+ years,677.07,100.6,25757.0
6,18000.0,36 months,5.32,A,MORTGAGE,125000.0,Fully Paid,1.36,2 years,542.07,4.9,4178.0
7,13000.0,36 months,11.14,B,RENT,46000.0,Fully Paid,26.87,10+ years,426.47,64.5,13425.0
8,18900.0,60 months,10.99,B,RENT,103000.0,Fully Paid,12.52,10+ years,410.84,32.9,18637.0
9,26300.0,36 months,16.29,C,MORTGAGE,115000.0,Fully Paid,23.69,3 years,928.40,82.4,22171.0
10,10000.0,36 months,13.11,B,RENT,95000.0,Fully Paid,12.04,2 years,337.47,64.4,4702.0
11,35000.0,36 months,14.64,C,MORTGAGE,130000.0,Fully Paid,12.19,8 years,1207.13,18.7,81263.0
12,7500.0,36 months,9.17,B,OWN,55000.0,Fully Paid,28.21,7 years,239.10,54.9,17838.0
13,35000.0,60 months,12.29,C,MORTGAGE,157000.0,Fully Paid,29.39,10+ years,783.70,94.9,113091.0
14,25975.0,36 months,6.62,A,MORTGAGE,65000.0,Fully Paid,9.18,9 years,797.53,7.2,5140.0
15,18000.0,36 months,8.39,A,MORTGAGE,45000.0,Fully Paid,12.81,8 years,567.30,11.7,551.0
16,32350.0,60 months,21.98,E,MORTGAGE,72000.0,Fully Paid,18.08,10+ years,893.11,78.4,23603.0
17,11200.0,60 months,12.29,C,MORTGAGE,81000.0,Fully Paid,12.87,10+ years,250.79,54.9,5874.0
18,34000.0,36 months,7.90,A,RENT,130580.0,Fully Paid,25.40,10+ years,1063.87,11.9,8767.0
19,20000.0,36 months,6.97,A,MORTGAGE,85000.0,Fully Paid,18.80,7 years,617.27,55.7,24195.0

In [23]:
df1.dtypes

loan_amnt         float64
term                  str
int_rate          float64
grade                 str
home_ownership        str
annual_inc        float64
loan_status           str
dti               float64
emp_length            str
dtype: object

In [24]:
df1.describe()

           loan_amnt       int_rate    annual_inc            dti
count  396030.000000  396030.000000  3.960300e+05  396030.000000
mean    14113.888089      13.639400  7.420318e+04      17.379514
std      8357.441341       4.472157  6.163762e+04      18.019092
min       500.000000       5.320000  0.000000e+00       0.000000
25%      8000.000000      10.490000  4.500000e+04      11.280000
50%     12000.000000      13.330000  6.400000e+04      16.910000
75%     20000.000000      16.490000  9.000000e+04      22.980000
max     40000.000000      30.990000  8.706582e+06    9999.000000

In [7]:
df1['home_ownership'].value_counts()

home_ownership
MORTGAGE    198348
RENT        159790
OWN          37746
OTHER          112
NONE            31
ANY              3
Name: count, dtype: int64

In [8]:
df1['grade'].value_counts()

grade
B    116018
C    105987
A     64187
D     63524
E     31488
F     11772
G      3054
Name: count, dtype: int64

Data fixes

In [9]:
df_pl = pl.from_pandas(df1)

In [16]:
df_pl.dtypes

[Float64, String, Float64, String, String, Float64, String, Float64, String]

removing % if the value had % in it
    #strip % and cast into float
    pl.col('int_rate')
        .str.replace('%','')
        .str.strip_chars()
        .cast(pl.Float64)
        .alias('int_rate_v1')


    pl.col('loan_status')
      .map_elements(lambda x: 1 if x == 'Charged Off' else 0, return_dtype=pl.Int8)
      .alias('default')

In [10]:
df_pl = df_pl.with_columns([
    #take number of years and convert to float
    pl.col('emp_length')
        .str.extract(r'(\d+)')
        .cast(pl.Float64)
        .alias('emp_length_v1')
    
    #remove months from term
    ,pl.col('term')
        .str.extract(r'(\d+)')
        .cast(pl.Float64)
        .alias('term_months')
    
])

In [11]:
df_pl.head()

shape: (5, 14)
┌───────────┬────────────┬──────────┬───────┬───┬────────────┬───────────┬────────────┬────────────┐
│ loan_amnt ┆ term       ┆ int_rate ┆ grade ┆ … ┆ revol_util ┆ revol_bal ┆ emp_length ┆ term_month │
│ ---       ┆ ---        ┆ ---      ┆ ---   ┆   ┆ ---        ┆ ---       ┆ _v1        ┆ s          │
│ f64       ┆ str        ┆ f64      ┆ str   ┆   ┆ f64        ┆ f64       ┆ ---        ┆ ---        │
│           ┆            ┆          ┆       ┆   ┆            ┆           ┆ f64        ┆ f64        │
╞═══════════╪════════════╪══════════╪═══════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ 10000.0   ┆  36 months ┆ 11.44    ┆ B     ┆ … ┆ 41.8       ┆ 36369.0   ┆ 10.0       ┆ 36.0       │
│ 8000.0    ┆  36 months ┆ 11.99    ┆ B     ┆ … ┆ 53.3       ┆ 20131.0   ┆ 4.0        ┆ 36.0       │
│ 15600.0   ┆  36 months ┆ 10.49    ┆ B     ┆ … ┆ 92.2       ┆ 11987.0   ┆ 1.0        ┆ 36.0       │
│ 7200.0    ┆  36 months ┆ 6.49     ┆ A     ┆ … ┆ 21.5       ┆ 5472.0    ┆ 6.0        ┆ 36.0       │
│ 24375.0   ┆  60 months ┆ 17.27    ┆ C     ┆ … ┆ 69.8       ┆ 24584.0   ┆ 9.0        ┆ 60.0       │
└───────────┴────────────┴──────────┴───────┴───┴────────────┴───────────┴────────────┴────────────┘

In [12]:
#encode home ownership
ho_map = {'MORTGAGE':1, 'RENT':2,'OWN':3,'NONE':4, 'ANY':5, 'OTHER':6}

#encode Grades
grades_map = {'A':1, 'B':2,'C':3,'D':4,'E':5,'F':6,'G':7}


df_pl = df_pl.with_columns([
    pl.col('home_ownership')
        .replace(ho_map)
        .cast(pl.Int8)
        .alias('homeowner_encoded')

    ,pl.col('grade')
        .replace(grades_map)
        .cast(pl.Int8)
        .alias('grade_encode')
])

In [13]:
#creating ratio features
df_pl = df_pl.with_columns([
    pl.when(pl.col('annual_inc') == 0)
    .then(None)
    .otherwise(pl.col('loan_amnt') / pl.col('annual_inc'))
    .alias('loan_to_inc')

    ,pl.when(pl.col('annual_inc') == 0)
    .then(None)
    .otherwise(pl.col('installment') / (pl.col('annual_inc') /12) )
    .alias('installments_to_inc')

    ,pl.when(pl.col('revol_util').is_null() | (pl.col('revol_util') == 0))
    .then(None)
    .otherwise(pl.col('revol_bal') / pl.col('revol_util'))
    .alias('credit_utilisation')
])

In [14]:
df_pl.head(20)

shape: (20, 19)
┌───────────┬────────────┬──────────┬───────┬───┬────────────┬────────────┬────────────┬───────────┐
│ loan_amnt ┆ term       ┆ int_rate ┆ grade ┆ … ┆ grade_enco ┆ loan_to_in ┆ installmen ┆ credit_ut │
│ ---       ┆ ---        ┆ ---      ┆ ---   ┆   ┆ de         ┆ c          ┆ ts_to_inc  ┆ ilisation │
│ f64       ┆ str        ┆ f64      ┆ str   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│           ┆            ┆          ┆       ┆   ┆ i8         ┆ f64        ┆ f64        ┆ f64       │
╞═══════════╪════════════╪══════════╪═══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 10000.0   ┆  36 months ┆ 11.44    ┆ B     ┆ … ┆ 2          ┆ 0.08547    ┆ 0.033793   ┆ 870.07177 │
│ 8000.0    ┆  36 months ┆ 11.99    ┆ B     ┆ … ┆ 2          ┆ 0.123077   ┆ 0.049049   ┆ 377.69230 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 8         │
│ 15600.0   ┆  36 months ┆ 10.49    ┆ B     ┆ … ┆ 2          ┆ 0.36231    ┆ 0.141293   ┆ 130.01084 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 6         │
│ 7200.0    ┆  36 months ┆ 6.49     ┆ A     ┆ … ┆ 1          ┆ 0.133333   ┆ 0.049033   ┆ 254.51162 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 8         │
│ 24375.0   ┆  60 months ┆ 17.27    ┆ C     ┆ … ┆ 3          ┆ 0.443182   ┆ 0.132945   ┆ 352.20630 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 4         │
│ …         ┆ …          ┆ …        ┆ …     ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 18000.0   ┆  36 months ┆ 8.39     ┆ A     ┆ … ┆ 1          ┆ 0.4        ┆ 0.15128    ┆ 47.094017 │
│ 32350.0   ┆  60 months ┆ 21.98    ┆ E     ┆ … ┆ 5          ┆ 0.449306   ┆ 0.148852   ┆ 301.05867 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 3         │
│ 11200.0   ┆  60 months ┆ 12.29    ┆ C     ┆ … ┆ 3          ┆ 0.138272   ┆ 0.037154   ┆ 106.99453 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 6         │
│ 34000.0   ┆  36 months ┆ 7.9      ┆ A     ┆ … ┆ 1          ┆ 0.260377   ┆ 0.097767   ┆ 736.72268 │
│           ┆            ┆          ┆       ┆   ┆            ┆            ┆            ┆ 9         │
│ 20000.0   ┆  36 months ┆ 6.97     ┆ A     ┆ … ┆ 1          ┆ 0.235294   ┆ 0.087144   ┆ 434.38061 │
└───────────┴────────────┴──────────┴───────┴───┴────────────┴────────────┴────────────┴───────────┘

In [48]:
df_pl.null_count()

shape: (1, 19)
┌───────────┬──────┬──────────┬───────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ loan_amnt ┆ term ┆ int_rate ┆ grade ┆ … ┆ grade_encode ┆ loan_to_inc ┆ installment ┆ credit_util │
│ ---       ┆ ---  ┆ ---      ┆ ---   ┆   ┆ ---          ┆ ---         ┆ s_to_inc    ┆ isation     │
│ u32       ┆ u32  ┆ u32      ┆ u32   ┆   ┆ u32          ┆ u32         ┆ ---         ┆ ---         │
│           ┆      ┆          ┆       ┆   ┆              ┆             ┆ u32         ┆ u32         │
╞═══════════╪══════╪══════════╪═══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 0         ┆ 0    ┆ 0        ┆ 0     ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 276         │
└───────────┴──────┴──────────┴───────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [15]:
null_counts = df_pl.null_count().unpivot(variable_name = 'column', value_name = 'null_counts')
null_counts.filter(pl.col('null_counts') > 0).sort('null_counts',descending = True)

shape: (6, 2)
┌─────────────────────┬─────────────┐
│ column              ┆ null_counts │
│ ---                 ┆ ---         │
│ str                 ┆ u32         │
╞═════════════════════╪═════════════╡
│ emp_length          ┆ 18301       │
│ emp_length_v1       ┆ 18301       │
│ credit_utilisation  ┆ 2489        │
│ revol_util          ┆ 276         │
│ loan_to_inc         ┆ 1           │
│ installments_to_inc ┆ 1           │
└─────────────────────┴─────────────┘

In [16]:
#imputing nulls
df_pl = df_pl.with_columns([
    pl.col('emp_length_v1').fill_null(-99999)

    ,pl.col('revol_util').fill_null(-99999)

    ,pl.col('credit_utilisation').fill_null(-99999)

])

In [17]:
#Encode final target variable
df_pl = df_pl.with_columns(
    pl.col('loan_status')
    .map_elements(lambda x: 1 if x == 'Charged Off' else 0, return_dtype=pl.Int8)
    .alias('default_flag')
)

In [20]:
df_pl.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ loan_amnt ┆ term      ┆ int_rate ┆ … ┆ loan_to_i ┆ installme ┆ credit_ut ┆ default_f │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ nc        ┆ nts_to_in ┆ ilisation ┆ lag       │
│ str       ┆ f64       ┆ str       ┆ f64      ┆   ┆ ---       ┆ c         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│           ┆           ┆           ┆          ┆   ┆           ┆ f64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 396030.0  ┆ 396030    ┆ 396030.0 ┆ … ┆ 396029.0  ┆ 396029.0  ┆ 396030.0  ┆ 396030.0  │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 14113.888 ┆ null      ┆ 13.6394  ┆ … ┆ 0.213413  ┆ 0.079244  ┆ -249.1756 ┆ 0.196129  │
│           ┆ 089       ┆           ┆          ┆   ┆           ┆           ┆ 33        ┆           │
│ std       ┆ 8357.4413 ┆ null      ┆ 4.472157 ┆ … ┆ 0.128325  ┆ 0.047939  ┆ 11452.174 ┆ 0.397068  │
│           ┆ 41        ┆           ┆          ┆   ┆           ┆           ┆ 354       ┆           │
│ min       ┆ 500.0     ┆ 36 months ┆ 5.32     ┆ … ┆ 0.000309  ┆ 0.000123  ┆ -99999.0  ┆ 0.0       │
│ 25%       ┆ 8000.0    ┆ null      ┆ 10.49    ┆ … ┆ 0.125714  ┆ 0.047592  ┆ 132.95950 ┆ 0.0       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 2         ┆           │
│ 50%       ┆ 12000.0   ┆ null      ┆ 13.33    ┆ … ┆ 0.2       ┆ 0.073635  ┆ 226.28491 ┆ 0.0       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ 6         ┆           │
│ 75%       ┆ 20000.0   ┆ null      ┆ 16.49    ┆ … ┆ 0.289655  ┆ 0.106077  ┆ 379.40133 ┆ 0.0       │
│ max       ┆ 40000.0   ┆ 60 months ┆ 30.99    ┆ … ┆ 40.0      ┆ 15.2998   ┆ 4.2973e6  ┆ 1.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
null_counts = df_pl.null_count().unpivot(variable_name = 'column', value_name = 'null_counts')
null_counts.filter(pl.col('null_counts') > 0).sort('null_counts',descending = True)

shape: (3, 2)
┌─────────────────────┬─────────────┐
│ column              ┆ null_counts │
│ ---                 ┆ ---         │
│ str                 ┆ u32         │
╞═════════════════════╪═════════════╡
│ emp_length          ┆ 18301       │
│ loan_to_inc         ┆ 1           │
│ installments_to_inc ┆ 1           │
└─────────────────────┴─────────────┘

#### Vectorisation and Numba

In [23]:
#testing loop using polars 

# standard for loop
# results = []
# for i in range(len(df_pl)):
#     results.append(df_pl['loan_amnt'][i] / df_pl['annual_inc'][i])

loan_inc_test = df_pl.with_columns(
    (pl.col('loan_amnt') / pl.col('annual_inc')).alias('loan_to_income_test')
)

In [30]:
#concept to understand on how to cut out outliers
inc_arr = df_pl['annual_inc'].to_numpy()
inc_arr_transformed = np.clip(inc_arr, 0, 99999)
loan_inc_test = df_pl.with_columns(
    pl.Series('annual_inc_v2', inc_arr_transformed)
)

In [43]:
def winsorise(df,col,lower_pct,higher_pct):
    arr = df[col].to_numpy()
    low = np.percentile(arr, lower_pct)
    high = np.percentile(arr, higher_pct)
    arr_clipped = np.clip(arr, low, high)
    df = df.with_columns(
        pl.Series(f"{col}_v2", arr_clipped)
    )
    return df

In [47]:
df_pl = winsorise(df_pl, 'annual_inc', 1, 95)
df_pl = winsorise(df_pl, 'dti', 1, 95)
df_pl = winsorise(df_pl, 'loan_to_inc', 1, 95)
df_pl = winsorise(df_pl, 'installments_to_inc', 1, 95)
df_pl = winsorise(df_pl, 'credit_utilisation', 1, 95)

In [ ]:
df_pl.describe()

shape: (9, 26)
┌────────────┬───────────┬───────────┬──────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ loan_amnt ┆ term      ┆ int_rate ┆ … ┆ dti_v2   ┆ loan_to_i ┆ installme ┆ credit_ut │
│ ---        ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---      ┆ nc_v2     ┆ nts_to_in ┆ ilisation │
│ str        ┆ f64       ┆ str       ┆ f64      ┆   ┆ f64      ┆ ---       ┆ c_v2      ┆ _v2       │
│            ┆           ┆           ┆          ┆   ┆          ┆ f64       ┆ ---       ┆ ---       │
│            ┆           ┆           ┆          ┆   ┆          ┆           ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╪══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 396030.0  ┆ 396030    ┆ 396030.0 ┆ … ┆ 396030.0 ┆ 396030.0  ┆ 396030.0  ┆ 396030.0  │
│ null_count ┆ 0.0       ┆ 0         ┆ 0.0      ┆ … ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 14113.888 ┆ null      ┆ 13.6394  ┆ … ┆ 17.20915 ┆ NaN       ┆ NaN       ┆ 283.51983 │
│            ┆ 089       ┆           ┆          ┆   ┆          ┆           ┆           ┆ 1         │
│ std        ┆ 8357.4413 ┆ null      ┆ 4.472157 ┆ … ┆ 7.801341 ┆ NaN       ┆ NaN       ┆ 202.38363 │
│            ┆ 41        ┆           ┆          ┆   ┆          ┆           ┆           ┆ 4         │
│ min        ┆ 500.0     ┆ 36 months ┆ 5.32     ┆ … ┆ 1.56     ┆ NaN       ┆ NaN       ┆ 15.982593 │
│ 25%        ┆ 8000.0    ┆ null      ┆ 10.49    ┆ … ┆ 11.28    ┆ NaN       ┆ NaN       ┆ 132.95950 │
│            ┆           ┆           ┆          ┆   ┆          ┆           ┆           ┆ 2         │
│ 50%        ┆ 12000.0   ┆ null      ┆ 13.33    ┆ … ┆ 16.91    ┆ NaN       ┆ NaN       ┆ 226.28491 │
│            ┆           ┆           ┆          ┆   ┆          ┆           ┆           ┆ 6         │
│ 75%        ┆ 20000.0   ┆ null      ┆ 16.49    ┆ … ┆ 22.98    ┆ NaN       ┆ NaN       ┆ 379.40133 │
│ max        ┆ 40000.0   ┆ 60 months ┆ 30.99    ┆ … ┆ 31.58    ┆ NaN       ┆ NaN       ┆ 802.15519 │
│            ┆           ┆           ┆          ┆   ┆          ┆           ┆           ┆ 6         │
└────────────┴───────────┴───────────┴──────────┴───┴──────────┴───────────┴───────────┴───────────┘